PREFIX rdf: <http://www.w4.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX oac: <http://www.openannotation.org/ns/>

PREFIX ro: <http://example.wf4ever-project.org/2011/ro/core#>
PREFIX rel: <http://example.wf4ever-project.org/2011/ro/relations#>
PREFIX ore: <http://www.openarchives.org/ore/terms/>

SELECT ?resource ?title ?authorOfTitle
WHERE { 
	?ann oac:hasTarget ?resource ;
	       a oac:DataAnnotation ;
	       oac:hasBody ?graph .
	?graph dc:creator ?creator .
	?creator foaf:name ?authorOfTitle .
	GRAPH ?graph {
		?ro dc:title ?title .
	}
}

